<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "minishop"
 *
 * Auto generated by Extension Builder 2020-06-23
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Minishop',
    'description' => 'Minishop for the lecture',
    'category' => 'plugin',
    'author' => 'winki',
    'author_email' => '',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.0-10.4.99',
            'static_info_tables' => '6.9.0-6.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
